In [117]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [118]:
heart_df=pd.read_csv('/content/heart.csv')
heart_df.head()

Age Sex ChestPainType  ...  Oldpeak  ST_Slope  HeartDisease
0   40   M           ATA  ...      0.0        Up             0
1   49   F           NAP  ...      1.0      Flat             1
2   37   M           ATA  ...      0.0        Up             0
3   48   F           ASY  ...      1.5      Flat             1
4   54   M           NAP  ...      0.0        Up             0

[5 rows x 12 columns]

In [119]:
heart_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Age             918 non-null    int64  
 1   Sex             918 non-null    object 
 2   ChestPainType   918 non-null    object 
 3   RestingBP       918 non-null    int64  
 4   Cholesterol     918 non-null    int64  
 5   FastingBS       918 non-null    int64  
 6   RestingECG      918 non-null    object 
 7   MaxHR           918 non-null    int64  
 8   ExerciseAngina  918 non-null    object 
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object 
 11  HeartDisease    918 non-null    int64  
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB


In [120]:
heart_df.describe()

Age   RestingBP  ...     Oldpeak  HeartDisease
count  918.000000  918.000000  ...  918.000000    918.000000
mean    53.510893  132.396514  ...    0.887364      0.553377
std      9.432617   18.514154  ...    1.066570      0.497414
min     28.000000    0.000000  ...   -2.600000      0.000000
25%     47.000000  120.000000  ...    0.000000      0.000000
50%     54.000000  130.000000  ...    0.600000      1.000000
75%     60.000000  140.000000  ...    1.500000      1.000000
max     77.000000  200.000000  ...    6.200000      1.000000

[8 rows x 7 columns]

In [121]:
corr=heart_df.corr()
corr['HeartDisease'][:-1]

Age            0.282039
RestingBP      0.107589
Cholesterol   -0.232741
FastingBS      0.267291
MaxHR         -0.400421
Oldpeak        0.403951
Name: HeartDisease, dtype: float64

In [122]:
heart_df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [123]:
heart_cat=heart_df.select_dtypes(include='object')
heart_cat

Sex ChestPainType RestingECG ExerciseAngina ST_Slope
0     M           ATA     Normal              N       Up
1     F           NAP     Normal              N     Flat
2     M           ATA         ST              N       Up
3     F           ASY     Normal              Y     Flat
4     M           NAP     Normal              N       Up
..   ..           ...        ...            ...      ...
913   M            TA     Normal              N     Flat
914   M           ASY     Normal              N     Flat
915   M           ASY     Normal              Y     Flat
916   F           ATA        LVH              N     Flat
917   M           NAP     Normal              N       Up

[918 rows x 5 columns]

In [124]:
from sklearn.preprocessing import OrdinalEncoder

# define ordinal encoding
encoder = OrdinalEncoder()
# transform data
result = encoder.fit_transform(heart_cat)
print(result)

[[1. 1. 1. 0. 2.]
 [0. 2. 1. 0. 1.]
 [1. 1. 2. 0. 2.]
 ...
 [1. 0. 1. 1. 1.]
 [0. 1. 0. 0. 1.]
 [1. 2. 1. 0. 2.]]


In [125]:
heart_cate=pd.DataFrame(result)
heart_cate.columns=["Sex", "Chestpaintype", "RestingEcq", "Exerciseangina","ST_slope"]

In [126]:
heart_cate.head()

Sex  Chestpaintype  RestingEcq  Exerciseangina  ST_slope
0  1.0            1.0         1.0             0.0       2.0
1  0.0            2.0         1.0             0.0       1.0
2  1.0            1.0         2.0             0.0       2.0
3  0.0            0.0         1.0             1.0       1.0
4  1.0            2.0         1.0             0.0       2.0

In [127]:
heart_df.shape

(918, 12)

In [128]:
heart_cate.shape

(918, 5)

In [129]:
heart_cate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Sex             918 non-null    float64
 1   Chestpaintype   918 non-null    float64
 2   RestingEcq      918 non-null    float64
 3   Exerciseangina  918 non-null    float64
 4   ST_slope        918 non-null    float64
dtypes: float64(5)
memory usage: 36.0 KB


In [130]:
heart = pd.concat([heart_df,heart_cate],axis='columns',ignore_index=False)
heart.head()

Age Sex ChestPainType  ...  RestingEcq  Exerciseangina  ST_slope
0   40   M           ATA  ...         1.0             0.0       2.0
1   49   F           NAP  ...         1.0             0.0       1.0
2   37   M           ATA  ...         2.0             0.0       2.0
3   48   F           ASY  ...         1.0             1.0       1.0
4   54   M           NAP  ...         1.0             0.0       2.0

[5 rows x 17 columns]

In [131]:
heart.isna().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
Sex               0
Chestpaintype     0
RestingEcq        0
Exerciseangina    0
ST_slope          0
dtype: int64

In [132]:
heart.head()

Age Sex ChestPainType  ...  RestingEcq  Exerciseangina  ST_slope
0   40   M           ATA  ...         1.0             0.0       2.0
1   49   F           NAP  ...         1.0             0.0       1.0
2   37   M           ATA  ...         2.0             0.0       2.0
3   48   F           ASY  ...         1.0             1.0       1.0
4   54   M           NAP  ...         1.0             0.0       2.0

[5 rows x 17 columns]

In [133]:
heart.drop(['Sex','ChestPainType','RestingECG','ExerciseAngina','ST_Slope'],axis=1,inplace=True)
heart.head()

Age  RestingBP  Cholesterol  ...  RestingEcq  Exerciseangina  ST_slope
0   40        140          289  ...         1.0             0.0       2.0
1   49        160          180  ...         1.0             0.0       1.0
2   37        130          283  ...         2.0             0.0       2.0
3   48        138          214  ...         1.0             1.0       1.0
4   54        150          195  ...         1.0             0.0       2.0

[5 rows x 11 columns]

In [134]:
from sklearn.preprocessing import MinMaxScaler
# define min max scaler
scaler = MinMaxScaler()
# transform data
scaled = scaler.fit_transform(heart)
print(scaled)

[[0.24489796 0.7        0.47927032 ... 0.5        0.         1.        ]
 [0.42857143 0.8        0.29850746 ... 0.5        0.         0.5       ]
 [0.18367347 0.65       0.46932007 ... 1.         0.         1.        ]
 ...
 [0.59183673 0.65       0.2172471  ... 0.5        1.         0.5       ]
 [0.59183673 0.65       0.39137645 ... 0.         0.         0.5       ]
 [0.20408163 0.69       0.29021559 ... 0.5        0.         1.        ]]


In [135]:
from sklearn.preprocessing import StandardScaler
# Initialise the Scaler
scaler = StandardScaler()
  
# To scale data
scaler.fit(heart)
from sklearn.preprocessing import normalize
normalize(heart)

array([[0.10914509, 0.38200781, 0.78857327, ..., 0.00272863, 0.        ,
        0.00545725],
       [0.16832129, 0.54962052, 0.61832309, ..., 0.00343513, 0.        ,
        0.00343513],
       [0.11260253, 0.39563052, 0.86125722, ..., 0.00608662, 0.        ,
        0.00608662],
       ...,
       [0.25354517, 0.57826092, 0.58270908, ..., 0.00444816, 0.00444816,
        0.00444816],
       [0.1749718 , 0.39905848, 0.72444463, ..., 0.        , 0.        ,
        0.00306968],
       [0.13347638, 0.48473   , 0.61469384, ..., 0.00351254, 0.        ,
        0.00702507]])

In [136]:
heart.head()

Age  RestingBP  Cholesterol  ...  RestingEcq  Exerciseangina  ST_slope
0   40        140          289  ...         1.0             0.0       2.0
1   49        160          180  ...         1.0             0.0       1.0
2   37        130          283  ...         2.0             0.0       2.0
3   48        138          214  ...         1.0             1.0       1.0
4   54        150          195  ...         1.0             0.0       2.0

[5 rows x 11 columns]

In [137]:
heart=heart.drop(['Cholesterol',],axis=1)

In [138]:
X=heart.drop(['HeartDisease'],axis=1)
X.dropna(inplace=True)
X

Age  RestingBP  FastingBS  ...  RestingEcq  Exerciseangina  ST_slope
0     40        140          0  ...         1.0             0.0       2.0
1     49        160          0  ...         1.0             0.0       1.0
2     37        130          0  ...         2.0             0.0       2.0
3     48        138          0  ...         1.0             1.0       1.0
4     54        150          0  ...         1.0             0.0       2.0
..   ...        ...        ...  ...         ...             ...       ...
913   45        110          0  ...         1.0             0.0       1.0
914   68        144          1  ...         1.0             0.0       1.0
915   57        130          0  ...         1.0             1.0       1.0
916   57        130          0  ...         0.0             0.0       1.0
917   38        138          0  ...         1.0             0.0       2.0

[918 rows x 9 columns]

In [139]:
Y=heart.iloc[:,6]
Y

0      1.0
1      2.0
2      1.0
3      0.0
4      2.0
      ... 
913    3.0
914    0.0
915    0.0
916    1.0
917    2.0
Name: Chestpaintype, Length: 918, dtype: float64

In [140]:

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score,recall_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,mean_absolute_error, r2_score

In [153]:
x_train , x_test , y_train , y_test = train_test_split(X,Y,test_size=0.2)

In [154]:
model=LogisticRegression(verbose=1)
model.fit(x_train,y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s finished


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=1,
                   warm_start=False)

In [143]:
#Test the model
predictions = model.predict(x_test)
print(predictions)# printing predictions

print()# Printing new line

#Check precision, recall, f1-score
print( classification_report(y_test, predictions) )

[0. 0. 2. 2. 0. 0. 0. 1. 2. 0. 2. 0. 0. 0. 0. 0. 0. 0. 2. 2. 0. 0. 1. 0.
 0. 2. 0. 0. 0. 0. 2. 0. 2. 2. 0. 1. 2. 0. 0. 2. 0. 2. 0. 0. 1. 0. 0. 2.
 0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 2. 2. 0. 2. 2. 2. 2. 2. 2. 2. 0. 0.
 0. 0. 0. 2. 1. 0. 2. 2. 0. 1. 0. 0. 2. 0. 0. 0. 2. 2. 0. 2. 0. 0. 0. 0.
 0. 0. 2. 0. 0. 1. 2. 2. 0. 0. 2. 2. 0. 0. 0. 0. 0. 1. 2. 2. 0. 1. 2. 1.
 2. 0. 2. 2. 0. 0. 0. 0. 0. 0. 0. 2. 0. 0. 0. 1. 1. 2. 1. 0. 0. 0. 2. 0.
 0. 0. 2. 1. 0. 1. 0. 0. 0. 0. 0. 1. 1. 2. 0. 0. 0. 0. 0. 0. 1. 0. 0. 2.
 0. 2. 0. 2. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 2. 2.]

              precision    recall  f1-score   support

         0.0       0.95      1.00      0.98       106
         1.0       1.00      0.81      0.89        26
         2.0       0.79      1.00      0.88        41
         3.0       0.00      0.00      0.00        11

    accuracy                           0.91       184
   macro avg       0.69      0.70      0.69       184
weighted avg       0.87      0.91      0.89       184



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [146]:
accuracy_score(y_test,predictions)

0.9130434782608695

In [161]:
from sklearn.model_selection import KFold

from sklearn.metrics import accuracy_score

#Implementing cross validation

k = 5
kf = KFold(n_splits=k, random_state=None)
model = RandomForestClassifier(criterion = 'entropy', class_weight={0:.5,1:.5}, max_depth = 5, min_samples_leaf=5)

acc_score = []

for train_index , test_index in kf.split(X):
    X_train , X_test = X.iloc[train_index,:],X.iloc[test_index,:]
    y_train , y_test = Y[train_index] , Y[test_index]
    
    model.fit(X_train,y_train)
    pred_values = model.predict(X_test)
    
    acc = accuracy_score(pred_values , y_test)
    acc_score.append(acc)
    
avg_acc_score = sum(acc_score)/k

print('accuracy of each fold - {}'.format(acc_score))
print('Accuracy : {}'.format(avg_acc_score))

accuracy of each fold - [0.9728260869565217, 0.9565217391304348, 0.9945652173913043, 0.9617486338797814, 0.9672131147540983]
Accuracy : 0.9705749584224282
